import { access, readFile, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const steamRoot = new URL("../dist/steam/", import.meta.url);
const planUrl = new URL("steam-upload-plan.json", steamRoot);
const appBuildUrl = new URL("app_build.vdf", steamRoot);
const uploadReportUrl = new URL("steam-upload-report.json", steamRoot);

function arg(name) {
  return process.argv.includes(name);
}

function env(name, fallback = "") {
  return process.env[name] || fallback;
}

async function exists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function redactArgs(args) {
  return args.map((value, index) => {
    const previous = args[index - 1];
    return previous === "+login" || index === 2 ? "<redacted>" : value;
  });
}

async function readPlan() {
  if (!(await exists(planUrl))) {
    throw new Error("Missing dist/steam/steam-upload-plan.json. Run npm run steam:plan first.");
  }
  return JSON.parse(await readFile(planUrl, "utf8"));
}

function makeSteamcmdArgs({ username, password }) {
  return [
    "+login",
    username,
    password,
    "+run_app_build",
    fileURLToPath(appBuildUrl),
    "+quit"
  ];
}

function assertUploadConfig({ steamcmdPath, username, password }) {
  const missing = [];
  if (!steamcmdPath) {
    missing.push("STEAMCMD_PATH");
  }
  if (!username) {
    missing.push("STEAM_USERNAME");
  }
  if (!password) {
    missing.push("STEAM_PASSWORD");
  }
  if (missing.length) {
    throw new Error(`Real upload requires ${missing.join(", ")}.`);
  }
}

async function runSteamcmd(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: "inherit"
    });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`SteamCMD exited with code ${code}`));
      }
    });
  });
}

const plan = await readPlan();
const steamcmdPath = env("STEAMCMD_PATH");
const username = env("STEAM_USERNAME");
const password = env("STEAM_PASSWORD");
const uploadRequested = env("STEAM_UPLOAD") === "1" && !arg("--dry-run");
const dryRun = !uploadRequested;

if (!dryRun) {
  assertUploadConfig({ steamcmdPath, username, password });
  if (!(await exists(steamcmdPath))) {
    throw new Error(`STEAMCMD_PATH does not exist: ${steamcmdPath}`);
  }
  if (!(await exists(appBuildUrl))) {
    throw new Error("Missing dist/steam/app_build.vdf. Run npm run steam:plan first.");
  }
}

const report = {
  appId: plan.appId,
  depotId: plan.depotId,
  branch: plan.branch,
  description: plan.description,
  generatedAt: new Date().toISOString(),
  mode: dryRun ? "dry-run" : "upload",
  steamcmdPath: steamcmdPath || "<STEAMCMD_PATH>",
  appBuildVdf: fileURLToPath(appBuildUrl),
  command: [
    steamcmdPath || "steamcmd",
    ...redactArgs(makeSteamcmdArgs({
      username: username || "<user>",
      password: password || "<password>"
    }))
  ],
  prerequisites: [
    "Steamworks app, depot, and branch created",
    "dist/steam/app_build.vdf generated by npm run steam:plan",
    "STEAMCMD_PATH points to a local SteamCMD executable",
    "STEAM_USERNAME and STEAM_PASSWORD are set for a build account with upload access",
    "Steam Guard is already trusted for this machine or handled by the build account policy"
  ]
};

await writeFile(uploadReportUrl, `${JSON.stringify(report, null, 2)}\n`);

if (dryRun) {
  console.log(`Steam upload dry run written to ${fileURLToPath(uploadReportUrl)}`);
  console.log(report.command.join(" "));
} else {
  await runSteamcmd(steamcmdPath, makeSteamcmdArgs({ username, password }));
  console.log(`Steam upload completed for app ${plan.appId} branch ${plan.branch}`);
}
